/** Curated starter dataset — expanded continuously as the DB grows. */
export const INGREDIENT_SEED = [
  {
    name: 'Niacinamide',
    aliases: ['Vitamin B3', 'Nicotinamide'],
    tagline: 'The multitasking barrier builder',
    purpose:
      'A form of Vitamin B3 that strengthens the skin barrier, regulates oil and evens tone.',
    description:
      'Niacinamide improves skin texture, reduces the look of pores and dark spots, and calms redness. It is well tolerated at 2–10% and pairs well with almost every other active.',
    benefits: [
      'Reduces acne and blemishes',
      'Improves skin barrier',
      'Minimizes pores',
      'Evens skin tone',
    ],
    sideEffects: ['Rare mild flushing at high concentrations'],
    safetyRating: 'safe',
    goodForSkinTypes: ['oily', 'combination', 'sensitive', 'normal', 'dry'],
    cautionForSkinTypes: [],
    concernsTargeted: ['acne', 'pores', 'dark_spots', 'redness', 'oiliness'],
    isCommonAllergen: false,
  },
  {
    name: 'Hyaluronic Acid',
    aliases: ['Sodium Hyaluronate'],
    tagline: 'The moisture magnet',
    purpose:
      'A humectant that binds up to 1000× its weight in water to plump and hydrate skin.',
    description:
      'Hyaluronic acid draws water into the upper layers of the skin, instantly improving bounce and softness. Apply on damp skin and seal with a moisturizer for best results.',
    benefits: ['Deep hydration', 'Plumps fine lines', 'Lightweight feel'],
    sideEffects: ['Can feel tacky in very dry climates without occlusion'],
    safetyRating: 'safe',
    goodForSkinTypes: ['dry', 'normal', 'sensitive', 'combination', 'oily'],
    cautionForSkinTypes: [],
    concernsTargeted: ['dryness', 'dullness', 'aging'],
    isCommonAllergen: false,
  },
  {
    name: 'Retinol',
    aliases: ['Vitamin A'],
    tagline: 'The gold-standard renewer',
    purpose:
      'A Vitamin A derivative that accelerates cell turnover and boosts collagen production.',
    description:
      'Retinol is one of the most studied anti-aging ingredients. Start low (0.1–0.3%) a few nights per week, always wear sunscreen, and avoid combining with strong acids while your skin adapts.',
    benefits: [
      'Smooths fine lines',
      'Fades dark spots',
      'Unclogs pores',
      'Boosts collagen',
    ],
    sideEffects: ['Dryness and peeling', 'Sun sensitivity', 'Purging period'],
    safetyRating: 'caution',
    goodForSkinTypes: ['normal', 'oily', 'combination'],
    cautionForSkinTypes: ['sensitive', 'dry'],
    concernsTargeted: ['aging', 'texture', 'acne', 'dark_spots'],
    isCommonAllergen: false,
  },
  {
    name: 'Salicylic Acid',
    aliases: ['BHA', 'Beta Hydroxy Acid'],
    tagline: 'The pore-clearing exfoliant',
    purpose:
      'An oil-soluble acid that exfoliates inside the pore to clear congestion and blackheads.',
    description:
      'Salicylic acid dissolves the debris that clogs pores, making it the go-to for oily, blemish-prone skin. Typical use is 0.5–2%; buffer with hydration to avoid over-drying.',
    benefits: ['Clears blackheads', 'Reduces breakouts', 'Smooths texture'],
    sideEffects: ['Dryness with overuse', 'Mild tingling'],
    safetyRating: 'safe',
    goodForSkinTypes: ['oily', 'combination'],
    cautionForSkinTypes: ['dry', 'sensitive'],
    concernsTargeted: ['acne', 'pores', 'oiliness', 'texture'],
    isCommonAllergen: false,
  },
  {
    name: 'Glycolic Acid',
    aliases: ['AHA'],
    tagline: 'The glow-giving resurfacer',
    purpose:
      'An alpha hydroxy acid that exfoliates the surface for brighter, smoother skin.',
    description:
      'Glycolic acid loosens dull surface cells to reveal fresher skin underneath. Great for uneven tone and texture; introduce gradually and use SPF daily.',
    benefits: ['Brightens tone', 'Softens texture', 'Fades post-acne marks'],
    sideEffects: ['Sun sensitivity', 'Irritation if over-used'],
    safetyRating: 'caution',
    goodForSkinTypes: ['normal', 'oily', 'combination'],
    cautionForSkinTypes: ['sensitive', 'dry'],
    concernsTargeted: ['dullness', 'texture', 'dark_spots'],
    isCommonAllergen: false,
  },
  {
    name: 'Ceramide NP',
    aliases: ['Ceramides'],
    tagline: 'The barrier bricklayer',
    purpose:
      'Skin-identical lipids that rebuild and reinforce the moisture barrier.',
    description:
      'Ceramides make up around half of the skin barrier. Topping them up strengthens resilience, locks in moisture and calms sensitivity — ideal for dry or compromised skin.',
    benefits: ['Repairs the barrier', 'Locks in hydration', 'Calms sensitivity'],
    sideEffects: [],
    safetyRating: 'safe',
    goodForSkinTypes: ['dry', 'sensitive', 'normal', 'combination', 'oily'],
    cautionForSkinTypes: [],
    concernsTargeted: ['dryness', 'redness', 'aging'],
    isCommonAllergen: false,
  },
  {
    name: 'Vitamin C',
    aliases: ['Ascorbic Acid', 'L-Ascorbic Acid'],
    tagline: 'The brightening antioxidant',
    purpose:
      'A potent antioxidant that brightens, protects from free radicals and supports collagen.',
    description:
      'Vitamin C defends skin against environmental damage and visibly fades dark spots. L-ascorbic acid at 10–20% is most potent; derivatives are gentler for sensitive skin.',
    benefits: ['Brightens', 'Fades dark spots', 'Antioxidant protection'],
    sideEffects: ['Tingling at high strength', 'Can oxidize in air/light'],
    safetyRating: 'safe',
    goodForSkinTypes: ['normal', 'oily', 'combination', 'dry'],
    cautionForSkinTypes: ['sensitive'],
    concernsTargeted: ['dark_spots', 'dullness', 'aging'],
    isCommonAllergen: false,
  },
  {
    name: 'Panthenol',
    aliases: ['Pro-Vitamin B5'],
    tagline: 'The soothing softener',
    purpose: 'A humectant and skin-soother that hydrates and supports healing.',
    description:
      'Panthenol strengthens the skin barrier and calms irritation, making it a quiet hero in moisturizers and soothing serums. Excellent for all skin types, including compromised skin.',
    benefits: ['Soothes irritation', 'Hydrates', 'Supports skin repair'],
    sideEffects: [],
    safetyRating: 'safe',
    goodForSkinTypes: ['sensitive', 'dry', 'normal', 'combination', 'oily'],
    cautionForSkinTypes: [],
    concernsTargeted: ['redness', 'dryness'],
    isCommonAllergen: false,
  },
  {
    name: 'Azelaic Acid',
    aliases: [],
    tagline: 'The redness and blemish whisperer',
    purpose:
      'A gentle multitasking acid that targets breakouts, redness and pigmentation.',
    description:
      'Azelaic acid is uniquely well tolerated: it calms rosacea-prone redness, fights acne bacteria and fades marks — all with minimal irritation at 10–20%.',
    benefits: ['Calms redness', 'Fights breakouts', 'Fades dark marks'],
    sideEffects: ['Mild itching at first use'],
    safetyRating: 'safe',
    goodForSkinTypes: ['sensitive', 'combination', 'oily', 'normal'],
    cautionForSkinTypes: [],
    concernsTargeted: ['redness', 'acne', 'dark_spots'],
    isCommonAllergen: false,
  },
  {
    name: 'Fragrance',
    aliases: ['Parfum'],
    tagline: 'Smells nice — skin may disagree',
    purpose: 'Added scent with no skincare benefit.',
    description:
      'Fragrance is the most common cause of cosmetic contact allergy. Fine for many, but if your skin is sensitive or reactive, fragrance-free formulas are the safer choice.',
    benefits: [],
    sideEffects: ['Contact allergy', 'Irritation', 'Sensitization over time'],
    safetyRating: 'caution',
    goodForSkinTypes: [],
    cautionForSkinTypes: ['sensitive', 'dry'],
    concernsTargeted: [],
    isCommonAllergen: true,
  },
  {
    name: 'Alcohol Denat.',
    aliases: ['Denatured Alcohol', 'SD Alcohol'],
    tagline: 'The quick-dry double-edged sword',
    purpose:
      'A solvent that gives products a fast-drying, weightless finish.',
    description:
      'In high concentrations denatured alcohol can dry the skin and disrupt the barrier. Low levels in well-formulated products are usually fine for oily skin, but dry and sensitive types should watch for it near the top of an ingredient list.',
    benefits: ['Lightweight texture', 'Helps actives penetrate'],
    sideEffects: ['Dryness', 'Barrier disruption with frequent use'],
    safetyRating: 'caution',
    goodForSkinTypes: ['oily'],
    cautionForSkinTypes: ['dry', 'sensitive', 'normal'],
    concernsTargeted: [],
    isCommonAllergen: false,
  },
  {
    name: 'Sodium Lauryl Sulfate',
    aliases: ['SLS'],
    tagline: 'The harsh foamer',
    purpose: 'A strong cleansing surfactant that creates rich foam.',
    description:
      'SLS cleans powerfully but can strip the skin barrier, leaving tightness and irritation — a common trigger for sensitive or dry skin. Gentler sulfate-free surfactants are widely available.',
    benefits: ['Effective cleansing'],
    sideEffects: ['Stripping', 'Irritation', 'Dryness'],
    safetyRating: 'avoid',
    goodForSkinTypes: [],
    cautionForSkinTypes: ['sensitive', 'dry', 'normal', 'combination', 'oily'],
    concernsTargeted: [],
    isCommonAllergen: true,
  },
  {
    name: 'Zinc Oxide',
    aliases: [],
    tagline: 'The mineral shield',
    purpose:
      'A broad-spectrum mineral UV filter that sits on the skin and reflects rays.',
    description:
      'Zinc oxide protects against UVA and UVB with very low irritation risk, making it the sunscreen filter of choice for sensitive and acne-prone skin.',
    benefits: ['Broad-spectrum SPF', 'Calming', 'Non-comedogenic'],
    sideEffects: ['Possible white cast on deeper skin tones'],
    safetyRating: 'safe',
    goodForSkinTypes: ['sensitive', 'oily', 'dry', 'normal', 'combination'],
    cautionForSkinTypes: [],
    concernsTargeted: ['redness', 'aging', 'dark_spots'],
    isCommonAllergen: false,
  },
  {
    name: 'Squalane',
    aliases: [],
    tagline: 'The featherweight moisturizer',
    purpose:
      'A skin-identical emollient that softens without clogging pores.',
    description:
      'Squalane mimics the skin’s own sebum, delivering silky moisture that suits every skin type — even oily and acne-prone. Stable, odorless and non-comedogenic.',
    benefits: ['Softens skin', 'Locks in moisture', 'Non-comedogenic'],
    sideEffects: [],
    safetyRating: 'safe',
    goodForSkinTypes: ['dry', 'sensitive', 'normal', 'combination', 'oily'],
    cautionForSkinTypes: [],
    concernsTargeted: ['dryness', 'texture'],
    isCommonAllergen: false,
  },
] as const;
